branch-defaults:
  default:
    environment: ScavengerRestService
  master:
    environment: node-express-env
environment-defaults:
  ScavengerRestService:
    branch: null
    repository: null
global:
  application_name: Scavenger.Rest
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
